CREATE TABLE IF NOT EXISTS TiposProductos(
	TipoProductoID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	Nombre text,
	Descripcion text,
	FechaCreacion timestamp,
	Activo BOOLEAN
);

CREATE TABLE IF NOT EXISTS Productos(
	ProductoID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    TipoProductoID INTEGER REFERENCES TiposProductos(TipoProductoID) ON DELETE CASCADE ON UPDATE CASCADE,
	Nombre text,
	Descripcion text,
	Precio decimal,
	FechaCreacion timestamp,
	Activo BOOLEAN
);

CREATE TABLE IF NOT EXISTS TiposClientes(
	TipoClienteID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	Nombre text,
	Descripcion text,
	FechaCreacion timestamp,
	Activo BOOLEAN
);

CREATE TABLE IF NOT EXISTS Clientes(
	ClienteID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    TipoClienteID INTEGER REFERENCES TiposClientes(TipoClienteID) ON DELETE CASCADE ON UPDATE CASCADE,
	Nombres text,
	Apellidos text,
	FechaNacimiento timestamp,
	FechaCreacion timestamp,
	Activo BOOLEAN
);

CREATE TABLE IF NOT EXISTS Facturas(
	FacturaID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	ClienteID INTEGER REFERENCES Clientes(ClienteID) ON DELETE CASCADE ON UPDATE CASCADE,
	TotalCrudo decimal,
	TotalDescuento decimal,
	FechaCreacion timestamp,
	Activo BOOLEAN
);

CREATE TABLE IF NOT EXISTS ProductosFacturas(
	ProductosFacturaID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	FacturaID INTEGER REFERENCES Facturas(FacturaID) ON DELETE CASCADE ON UPDATE CASCADE,
	ProductoID INTEGER REFERENCES Productos(ProductoID) ON DELETE CASCADE ON UPDATE CASCADE,
	FechaCreacion timestamp,
	Activo BOOLEAN
);

CREATE TABLE IF NOT EXISTS Reglas(
	ReglaID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	Nombre text,
	FechaCreacion timestamp,
	Activo BOOLEAN
);

CREATE TABLE IF NOT EXISTS Descuentos(
	DescuentoID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	Nombre text,
	Tipo text,
	Valor decimal,
	FechaCreacion timestamp,
	Activo BOOLEAN
);

CREATE TABLE IF NOT EXISTS ReglasDescuentos(
	ReglaDescuentoID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	DescuentoID INTEGER REFERENCES Descuentos(DescuentoID) ON DELETE CASCADE ON UPDATE CASCADE,
	ReglaID INTEGER REFERENCES Reglas(ReglaID) ON DELETE CASCADE ON UPDATE CASCADE,
	Criterio text,
	FechaCreacion timestamp,
	Activo BOOLEAN
);

CREATE TABLE IF NOT EXISTS DescuentosAplicados(
	DescuentoAplicadoID integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	DescuentoID INTEGER REFERENCES Descuentos(DescuentoID) ON DELETE CASCADE ON UPDATE CASCADE,
	FacturaID INTEGER REFERENCES Facturas(FacturaID) ON DELETE CASCADE ON UPDATE CASCADE,
	FechaCreacion timestamp,
	Activo BOOLEAN
);







INSERT into TiposProductos (Nombre, Descripcion, FechaCreacion, Activo) VALUES (N'Comestible', N'Algo comestible', CAST(N'2021-10-30T19:47:03.390' AS timestamp), true);
INSERT into TiposProductos (Nombre, Descripcion, FechaCreacion, Activo) VALUES (N'Electrodomestico', N'Un articulo electrico para el hogar', CAST(N'2021-10-30T19:47:03.390' AS timestamp), true);

INSERT into Productos (TipoProductoID, Nombre, Descripcion, Precio, FechaCreacion, Activo) VALUES (1, N'Manzana', N'Manzana de la montaña', 59.9, CAST(N'2021-10-30T19:47:03.390' AS timestamp), true);
INSERT into Productos (TipoProductoID, Nombre, Descripcion, Precio, FechaCreacion, Activo) VALUES (2, N'Laptop', N'PC portatil', 12000.00, CAST(N'2021-10-30T19:47:03.390' AS timestamp), true);


INSERT into TiposClientes (Nombre, Descripcion, FechaCreacion, Activo) VALUES (N'Afiliado', N'Un afiliado de la empresa', CAST(N'2021-10-30T19:47:03.390' AS timestamp), true);
INSERT into TiposClientes (Nombre, Descripcion, FechaCreacion, Activo) VALUES (N'Empleado', N'Un empleado de la empresa', CAST(N'2021-10-30T19:47:03.390' AS timestamp), true);
INSERT into TiposClientes (Nombre, Descripcion, FechaCreacion, Activo) VALUES (N'Consumidor', N'Un empleado de la empresa', CAST(N'2021-10-30T19:47:03.390' AS timestamp), true);

INSERT into Clientes (TipoClienteID, Nombres, Apellidos, FechaNacimiento, FechaCreacion, Activo) VALUES (1, N'Mauricio Michael', N'Mojica Nuñez', CAST(N'2000-01-03T19:47:03.390' AS timestamp), CAST(N'2021-10-30T19:47:03.390' AS timestamp) ,true);
INSERT into Clientes (TipoClienteID, Nombres, Apellidos, FechaNacimiento, FechaCreacion, Activo) VALUES (2, N'Roberto Manuel', N'Ramirez Nuez', CAST(N'2002-06-03T19:47:03.390' AS timestamp), CAST(N'2021-10-30T19:47:03.390' AS timestamp),true);
INSERT into Clientes (TipoClienteID, Nombres, Apellidos, FechaNacimiento, FechaCreacion, Activo) VALUES (3, N'Yosiel Carmen', N'Pandora Leico', CAST(N'2002-06-03T19:47:03.390' AS timestamp), CAST(N'2016-10-30T19:47:03.390' AS timestamp),true);

INSERT into Reglas (Nombre, FechaCreacion, Activo) VALUES (N'Por tipo de cliente', CAST(N'2021-10-30T19:47:03.390' AS timestamp) ,true);
INSERT into Reglas (Nombre, FechaCreacion, Activo) VALUES (N'Por tipo de producto', CAST(N'2021-10-30T19:47:03.390' AS timestamp) ,true);
INSERT into Reglas (Nombre, FechaCreacion, Activo) VALUES (N'Por nombre de cliente', CAST(N'2021-10-30T19:47:03.390' AS timestamp) ,true);
INSERT into Reglas (Nombre, FechaCreacion, Activo) VALUES (N'Por apellido de cliente', CAST(N'2021-10-30T19:47:03.390' AS timestamp) ,true);
INSERT into Reglas (Nombre, FechaCreacion, Activo) VALUES (N'Por edad de cliente', CAST(N'2021-10-30T19:47:03.390' AS timestamp) ,true);
INSERT into Reglas (Nombre, FechaCreacion, Activo) VALUES (N'Por tiempo en la tienda del cliente', CAST(N'2021-10-30T19:47:03.390' AS timestamp) ,true);
INSERT into Reglas (Nombre, FechaCreacion, Activo) VALUES (N'Por cantidad total factura', CAST(N'2021-10-30T19:47:03.390' AS timestamp) ,true);
INSERT into Reglas (Nombre, FechaCreacion, Activo) VALUES (N'Por fecha actual', CAST(N'2021-10-30T19:47:03.390' AS timestamp) ,true);
INSERT into Reglas (Nombre, FechaCreacion, Activo) VALUES (N'Por nombre de producto', CAST(N'2021-10-30T19:47:03.390' AS timestamp) ,true);
INSERT into Reglas (Nombre, FechaCreacion, Activo) VALUES (N'No criterio', CAST(N'2021-10-30T19:47:03.390' AS timestamp) ,true);

INSERT into Descuentos (Nombre, Tipo, Valor, FechaCreacion, Activo) VALUES (N'10% por ser afiliado', N'Porcentual', 10 , CAST(N'2021-10-30T19:47:03.390' AS timestamp) ,true);
INSERT into Descuentos (Nombre, Tipo, Valor, FechaCreacion, Activo) VALUES (N'30% por ser empleado', N'Porcentual', 30 , CAST(N'2021-10-30T19:47:03.390' AS timestamp) ,true);
INSERT into Descuentos (Nombre, Tipo, Valor, FechaCreacion, Activo) VALUES (N'5% por ser cliente por mas de 2 años', N'Porcentual', 5 , CAST(N'2021-10-30T19:47:03.390' AS timestamp) ,true);
INSERT into Descuentos (Nombre, Tipo, Valor, FechaCreacion, Activo) VALUES (N'5 dolares menos cada 100', N'Cada 100', 5 , CAST(N'2021-10-30T19:47:03.390' AS timestamp) ,true);


INSERT into ReglasDescuentos (DescuentoID, ReglaID, Criterio, FechaCreacion, Activo) VALUES (1, 1, N'=|Afiliado' , CAST(N'2021-10-30T19:47:03.390' AS timestamp) ,true);
INSERT into ReglasDescuentos (DescuentoID, ReglaID, Criterio, FechaCreacion, Activo) VALUES (2, 1, N'=|Empleado' , CAST(N'2021-10-30T19:47:03.390' AS timestamp) ,true);
INSERT into ReglasDescuentos (DescuentoID, ReglaID, Criterio, FechaCreacion, Activo) VALUES (3, 6, N'>=|2' , CAST(N'2021-10-30T19:47:03.390' AS timestamp) ,true);
INSERT into ReglasDescuentos (DescuentoID, ReglaID, Criterio, FechaCreacion, Activo) VALUES (4, 10, N'' , CAST(N'2021-10-30T19:47:03.390' AS timestamp) ,true);